In [202]:
import pandas as pd
import numpy as np
df=pd.read_csv("combined.csv")

def convertToFloat(x):
    x=x.strip()
    if x=="-" or x=="NR" or x=='' or x=="." or x=="" or x==' ':
        return 0
    else:
        
        return float(x)
df["rain"]=df["Rain"].apply(convertToFloat)
# import datetime
df.pop("Rain")
aldf=df[df.District=="Alangayam"]
# df["month"]=df["Date"].apply(lambda x:datetime.datetime.strptime(x,"%Y-%m-%d").month)
# df["year"]=df["Date"].apply(lambda x: datetime.datetime.strptime(x,"%Y-%m-%d").year)
# df["day"]=df["Date"].apply(lambda x: datetime.datetime.strptime(x,"%Y-%m-%d").day)

In [172]:
dataset=aldf[["rain"]].values
dataset 

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [109]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from tensorflow import keras

In [203]:
np.random.seed(7)
scaler = MinMaxScaler(feature_range=(0, 1))
dataset=scaler.fit_transform(dataset)

In [204]:
def CreateDataset(dataset,lookback):
    DataX=[]
    DataY=[]
    for i in range(len(dataset)-lookback-1):
        DataX.append(dataset[i:(lookback+i),0])
        DataY.append(dataset[(lookback+i),0])
    return np.array(DataX),np.array(DataY)

In [205]:
trainX

array([[[0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.]]])

In [206]:
trainsize=3287
testsize=365
train, test = dataset[0:trainsize,:], dataset[trainsize:len(dataset),:]

In [216]:
look_back=30
trainX,trainY=CreateDataset(train,look_back)
testX,testY=CreateDataset(test,look_back)


In [217]:
# reshape input to be [samples, time steps, features]
trainX = np.reshape(trainX, (trainX.shape[0], 1, trainX.shape[1]))
testX = np.reshape(testX, (testX.shape[0], 1, testX.shape[1]))

In [218]:
2=@

SyntaxError: invalid syntax (<ipython-input-218-7474edad756f>, line 1)

In [220]:
model = Sequential()

opt = keras.optimizers.Adam()
model.add(LSTM(4, input_shape=(1, look_back)))
model.add(Dense(1,activation="relu"))
model.compile(loss='mean_absolute_error', optimizer=opt)
model.fit(trainX, trainY, epochs=100, batch_size=1, verbose=2)

Epoch 1/100
3256/3256 - 3s - loss: 0.0177
Epoch 2/100
3256/3256 - 3s - loss: 0.0176
Epoch 3/100
3256/3256 - 3s - loss: 0.0176
Epoch 4/100
3256/3256 - 3s - loss: 0.0176
Epoch 5/100
3256/3256 - 3s - loss: 0.0176
Epoch 6/100
3256/3256 - 3s - loss: 0.0176
Epoch 7/100
3256/3256 - 3s - loss: 0.0176
Epoch 8/100
3256/3256 - 3s - loss: 0.0176
Epoch 9/100
3256/3256 - 3s - loss: 0.0176
Epoch 10/100
3256/3256 - 3s - loss: 0.0176
Epoch 11/100
3256/3256 - 3s - loss: 0.0176
Epoch 12/100
3256/3256 - 3s - loss: 0.0176
Epoch 13/100
3256/3256 - 3s - loss: 0.0176
Epoch 14/100
3256/3256 - 3s - loss: 0.0176
Epoch 15/100
3256/3256 - 3s - loss: 0.0176
Epoch 16/100
3256/3256 - 3s - loss: 0.0176
Epoch 17/100
3256/3256 - 3s - loss: 0.0176
Epoch 18/100
3256/3256 - 3s - loss: 0.0176
Epoch 19/100
3256/3256 - 3s - loss: 0.0176
Epoch 20/100
3256/3256 - 3s - loss: 0.0176
Epoch 21/100
3256/3256 - 3s - loss: 0.0176
Epoch 22/100
3256/3256 - 3s - loss: 0.0176
Epoch 23/100
3256/3256 - 3s - loss: 0.0176
Epoch 24/100
3256/32

In [221]:
trainPredict = model.predict(trainX)
testPredict = model.predict(testX)

In [222]:
trainPredict = scaler.inverse_transform(trainPredict)
trainY = scaler.inverse_transform([trainY])
testPredict = scaler.inverse_transform(testPredict)
testY = scaler.inverse_transform([testY])

In [224]:
from sklearn.metrics import mean_squared_error


ypred=testPredict.reshape(334)
ty=testY.reshape(334)

In [225]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(ty,ypred)

2.8140718562874247

In [226]:
ypred

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.